---
title: "Schedule HT19"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, message=FALSE, warning=FALSE}
suppressPackageStartupMessages(library(jsonlite))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(knitr))

# Byt https mot aktuell schemalänk nedan
TimeEdit_URL <- "https://cloud.timeedit.net/su/web/stud1/ri107455X48Z06Q5Z16g3Y05y5006Y48Q02gQY6Q55727.json"
datum <- unique(fromJSON(TimeEdit_URL, flatten = TRUE)$reservations) %>% 
    mutate(veckodag = weekdays(as.Date(startdate)), 
           tid = paste(starttime, endtime, sep = "-")) %>% 
    select(veckodag, startdate, tid) %>% 
    distinct() # %>% apply(., 1, paste, collapse = ", ")
topics <- c(
    "[Introduction. Software, GitHub and Markdown.](Class/day1.html) [[Slides](slides/slide1.html)]",
    "[Tidyverse: Basic dplyr and ggplot2.](Class/day2.html) [[Slides](slides/slide2.html)]",
    "[Tidyverse: group_by and summarise, more ggplot2.](Class/day3.html)",
    "[Exploratory data analysis](Class/day4.html)",
    "[Cleaning data: Tidy data. Long to wide and back.](Class/day5.html)",
    "[Relational data: Combining tables with dplyr joins.](Class/day6.html) <br>",
        "[Relational data: SQL basics](Class/day7.html).",
    "[Exploring high-dimensional data: Principal components and clustering](Class/day8.html)",
    "[Text data: Regular expressions.<br>09:15-10:00 Guest lecture: Benjamin Allévius, King](Class/day9.html)",
    "[Using APIs: httr, JSON and XML.](Class/day10.html)",
    "[Web-scraping: Basic rvest.](Class/day11.html)",
    "[R Programming: Programming with functions.](Class/day12.html)<br>09:15-10:00 Guest lecture: Magnus Gudmundson, Watercircles",
    "[R Programming: Functional programming with purrr.](Class/day13.html)",
    "[Presenting: Principles of visualisation.](Class/day14.html)",
    "Exam.",
    "Re-exam",
    "Project presentation.")

##
##Remove all links from topics. 
##@param topics Vector of characters containing the lecture info
##@param from_lecture_number First lecture number to remove URLs from.
##
remove_url_from_topics <- function(topics, from_lecture_number=1) {
    stopifnot(from_lecture_number>0)
    
    result <- stringr::str_replace(topics[from_lecture_number:length(topics)], "\\([^)]*\\)", "")
    result <- stringr::str_replace(result, "\\[([^)]*)\\]", "\\1")
    
    return(c(topics[seq_len(from_lecture_number-1)], result))
}

##Remove URLs. Increment this for every lecture we do.
from_lecture_number <- 8#length(topics) 
topics <- remove_url_from_topics(topics, from_lecture_number=from_lecture_number)
```

```{r TIMEEDIT, echo = FALSE, message=FALSE, warning=FALSE, results="asis"}
cat(paste0("<p>The schedule of the MT5013 HT2019 course is automatically fetched from [TimeEdit](",stringr::str_replace(TimeEdit_URL,"\\.json",""),").<br><br></p>"))
```
```{r KABLESCHEDULE, echo = FALSE}
kable(data.frame(Lecture = c(seq_len(length(topics)-3),rep("",2),"15"), Day = paste(datum$veckodag, datum$startdate, sep = ", "), Time = datum$tid, Topic = topics))
```
